openapi: 3.0.3
info:
  title: Amazing Gateway Service
  description: Amazing Gateway Service
  version: 1.0.0
servers:
  - url: 'http://localhost:9005'
    description: Local server
paths:

  /users/{pseudo}:

    parameters:
      - name: pseudo
        in: path
        required: true
        schema:
          type: string
        description: Pseudo of the user

    post:
      summary: Create a user
      requestBody:
        description: User to create
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/user'
      responses:
        400:
          description: Invalid user
        409:
          description: User already exists
        201:
          description: Created user

    delete:
      summary: Delete a user
      responses:
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: User not found
        200:
          description: User deleted

  /wishlist/{pseudo}/{productId}:

    parameters:
      - name: pseudo
        in: path
        required: true
        schema:
          type: string
        description: Pseudo of the user

    post:
      summary: Add a product to the wishlist
      requestBody:
        description: Wishlist to add
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/wishlist'
      responses:
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: User not found
        200:
          description: Product added to the wishlist

components:
  schemas:
    user:
      type: object
      properties:
        pseudo:
          type: string
        firstname:
          type: string
        lastname:
          type: string
        password:
          type: string
      example:
        pseudo: "myPseudo"
        firstname: "myFirstname"
        lastname: "myLastname"
        password: "myPassword"

    wishlist:
        type: object
        properties:
          pseudo:
            type: string
          productId:
            type: string
        example:
          pseudo: "myPseudo"
          productId: 1